### ISSUE TITLE
Question: How to make stylelint --fix to work with stylelint-declaration-strict-value

### ISSUE THREAD

**Issue by imvetri** [AndyOGo/stylelint-declaration-strict-value#18]
Hi,

First of all great plugin!.

I am using your plugin along with stylelint to give warning whenever variables are not used for margins. I was thinking whether is it possible to automatically change the values based on the warnings?

**Comment by AndyOGo** [comment]
Hi,

Thank you.
The limitations of autofixing `--fix` option is that it only works with static rules (like using semi colons or not, tabs or spaces for indentation, etc).
All dynamic rules can't be auto fixed, because you as a programmer have to:
1. define a `$color-variable`
2. and then decide where to use it

Hope that answers your question.

**Comment by imvetri** [comment]
@AndyOGo Thanks for the clarification. 

As you suggested yes; **auto fixing** `--fix` should be a separate logic handled separately. I tried with sample working version where `margin-left: 5px` be transformed to `margin-left: $margin-xx-small`.  Here is the link to the [commit](https://github.com/imvetri/stylelint-declaration-strict-value/commit/451de00d89c6eac0b3ac48ea0173d7215906b297) 


Do you think we can have the [usage](https://github.com/imvetri/stylelint-declaration-strict-value/commit/451de00d89c6eac0b3ac48ea0173d7215906b297) be changed so that programmer's logic of auto fixing be configurable ?

I am open to contribute if you think it is a good idea.

**Comment by AndyOGo** [comment]
@imvetri 
Thanks for your feedback.

I saw your commit.
Well the thing is your developed a solution here for one specific case, which I think is okay.
But not as part of this plugin. I would suggest to write a simple PostCSS plugin which transforms values to variables.

IMHO a generic solution to fit everyone's needs is just because of the factor of free will of any programmer not feasible.

**Comment by imvetri** [comment]
@AndyOGo Thanks for the suggestion. 

Before I go for writing simple PostCSS plugin, I gave a try of making it generic. Here is the link to the [commit](https://github.com/imvetri/stylelint-declaration-strict-value/commit/f4361ca6e9b748a7178c83ab0ca48db89d3c1d0d). Please let me know what do you think.

**Comment by AndyOGo** [comment]
@imvetri 
Because this is rather complex/individual I added a new readme section:
https://github.com/AndyOGo/stylelint-declaration-strict-value#autofix-support

Hope this helps you
